### ISSUE TITLE
Failing pipeline due to new flake8-bugbear version 

### ISSUE THREAD

**Issue by cr-xu** [desy-ml/cheetah#118]
It looks like the [pipeline](https://github.com/desy-ml/cheetah/actions/runs/7538619809/job/20519500818) is failing due to the [new flake8-bugbear version](https://github.com/PyCQA/flake8-bugbear/releases/tag/24.1.15).

This needs to be fixed before #94

**Comment by jank324** [comment]
This is a bit weird. The flake8 warning is:

```bash
./cheetah/converters/dontbmad.py:429:35: B038 editing a loop's mutable iterable often leads to unexpected results/bugs
```

But I would argue that this loop doesn't actually edit its iterable 🤔 

```python
for property in properties:
        assert property in understood, (
            f"Property {property} with value {properties[property]} for element type"
            f" {properties['element_type']} is currently not understood. Other values"
            f" in properties are {properties.keys()}."
```

**Comment by cr-xu** [comment]
Looks like it's a common issue: https://github.com/PyCQA/flake8-bugbear/issues/451 
For now, shall we add `--extend-ignore=B038` or just leave it until they update to fix this issue?

**Comment by jank324** [comment]
Ignoring it is probably the way to go then, but I would ignore it inline.
