### ISSUE TITLE
Use pre-commit instead of a standalone format Gtihub action in CI/CD

### ISSUE THREAD

**Issue by cr-xu** [desy-ml/cheetah#147]
This format pipeline failed even with local pre-commit hooks
https://github.com/desy-ml/cheetah/actions/runs/8876067584/job/24366827967

I think the reason is a version conflict in black (22.x -> 24.x)

So to make things easier in the future, there are different ways to proceed:
1. Regularly update the `.pre-commit-config.yaml` so that the versions are compatible with the CI/CD workflow 
2. Another way around is to fix the formatting tools' version to the ones in `.pre-commit-config.yaml`
3. Replace the format action with a pre-commit action which does formatting check and refomat things automatically if possible.

**Comment by jank324** [comment]
Are you sure this is a version issue? The formatting fail looks to me much more like it's a line length issue. Though I'm not sure why this would occur. `.pre-commit-config.yaml` doesn't define the line length for black (only for isort) ... but the default should be 88 as we use it.

Anyway ... is there any reason `rev` is fixed for `black` and `isort`. If we don't fix it, everything should automatically use the most recent version, which is my preferred outcome.
