### ISSUE TITLE
NumPy `v2.0.0` compatibility

### ISSUE THREAD

**Issue by jank324** [desy-ml/cheetah#177]
There has been a [breaking new release of NumPy](https://github.com/numpy/numpy/releases/tag/v2.0.0). Running the tests with that seems to produce 7 errors at the moment.

We should (a) fix those and (b) if that seems to take more than a little bit of work pin `numpy<=1.26.4`.

**Comment by jank324** [comment]
Fun fact: Cheetah is fully compatible with the new NumPy as is. I was just running the tests with an old version of `h5py` that wasn't compatible. So I'm closing the issue.

**Comment by Hespe** [comment]
On Windows, PyTorch still doesn't properly support NumPy 2.0. https://github.com/pytorch/pytorch/issues/128860
As such, we currently get 51 test failures that all go away if NumPy 1.26 is used.

> A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.0 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
>
> If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2.

**Comment by jank324** [comment]
In that case this issue should remain open until that bug is (a) fixed or (b) PyTorch pins NumPy in its requirements.
