### ISSUE TITLE
Refactor `gamma`

### ISSUE THREAD

**Issue by jank324** [desy-ml/cheetah#180]
We compute `gamma` in quite a few places (e.g. `track_methods.py` -> `base_r_matrix`. The `Beam` class already has a `relativistic_gamma` property which we should use instead.

**Comment by Hespe** [comment]
This requires access to the specific beam, right? Seems like that would be a breaking change for the signature of the `element.transfer_map` or `track_methods.base_r_matrix` functions. Or is there a way to get access to the beam that I am currently missing?

**Comment by jank324** [comment]
Ah ... good point. There is not ... so the computation can just stay as is. I'm also not finding any other location where the proposed refactoring actually makes sense, so I think we can just close this issue.
