### ISSUE TITLE
Dipole element name overwriting

### ISSUE THREAD

**Issue by jp-ga** [desy-ml/cheetah#181]
I was checking `dipole.py` and saw this: [https://github.com/desy-ml/cheetah/blob/ff3430b25dac3d62c8515313d014d29fafff6b02/cheetah/accelerator/dipole.py#L77](https://github.com/desy-ml/cheetah/blob/ff3430b25dac3d62c8515313d014d29fafff6b02/cheetah/accelerator/dipole.py#L77)

It might be overwriting the name generated from the Element class init : [https://github.com/desy-ml/cheetah/blob/ff3430b25dac3d62c8515313d014d29fafff6b02/cheetah/accelerator/element.py#L37](https://github.com/desy-ml/cheetah/blob/ff3430b25dac3d62c8515313d014d29fafff6b02/cheetah/accelerator/element.py#L37)

**Comment by jank324** [comment]
Yeah ... I think this is an issue and the line in `quadrupole.py` should be removed. We should also check if other elements do the same thing.
