### ISSUE TITLE
Position to add new elements/ new tracking methods to existing elements

### ISSUE THREAD

**Issue by cr-xu** [desy-ml/cheetah#219]
As we are now including more elemnts and tracking methods into Cheetah, we should agree on a standard to place them, i.e. shall we 
-  implement them in different classes and provide easy convert methods, or
-  implement in the same class with an optional attribute to switch the method, like `Screen` with KDE

An example now would be to use exact map for drift instead of the linearized map we currently have.

This is also related to #139, but that PR can be merged first and we can refactor later.

**Comment by jank324** [comment]
So for the record, what we just agreed on in the meeting:
 - Different track methods should be toggled via switches, like it is done in `Screen` wit KDE and in #139.
 - If elements share track methods, they can be made reusable by putting them in a place that we might call something like `cheetah.physics.my_amazing_track_method`.

**Comment by cr-xu** [comment]
I think we can close this issue. In general, these discussions should probably be included in the _Contributing_ section on the documentation page.
