### ISSUE TITLE
Transfer map inaccuracy for fringe field effect for dipole element

### ISSUE THREAD

**Issue by zihan-zh** [desy-ml/cheetah#259]
There is a missing coefficient in the fringe field effect calculation for dipole magnets in the current implementation. 
According to the formula 18.16 in [Bmad manual](https://www.classe.cornell.edu/bmad/manual.html), a coefficient of 2 should be implemented into the phi value calc in `Dipole._transfer_map_enter` and `Dipole._transfer_map_exit`.

**Comment by cr-xu** [comment]
I believe this is due to different naming conventions. We used the OCELOT parameters where `gap(cheetah, ocelot) = 2 * hgap (MAD, BMAD)`, See [this comment here](https://github.com/desy-ml/cheetah/blob/3038c7b51b40a7dd36c4a2c105dbd030c86da743/cheetah/accelerator/dipole.py#L31)

**Comment by cr-xu** [comment]
So the actual issue is the incorrect converter class...
This should be fixed: https://github.com/desy-ml/cheetah/blob/3038c7b51b40a7dd36c4a2c105dbd030c86da743/cheetah/converters/bmad.py#L148
