### ISSUE TITLE
Error when tracking `ParameterBeam` through segment that is on CPU?

### ISSUE THREAD

**Issue by jank324** [desy-ml/cheetah#68]
I found this in the `ParameterBeam` part of the `Element.__call__` function:

```python
if self.device != "cpu":
    raise DeviceError
```

I think this doesn't make any sense (though I'm not sure). We should look into this at some point.

**Comment by jank324** [comment]
Also ... this is checked after the actual calculations, which would have thrown an error about device mismatches already. We should really fix this!

**Comment by cr-xu** [comment]
I think initially the reasoning was that it doesn't make sense to shift the `ParameterBeam` to GPU, because the overhead would be more time-consuming than the actual tracking. But yes, it doesn't make sense to through an error, I'll just fix this.
