### ISSUE TITLE
Establish testing

### ISSUE THREAD

**Issue by jank324** [desy-ml/cheetah#7]
### 🚀 Feature Request

Cheetah needs some sort of software tests that ensure everything works correctly and the computed results agree with other simulations such as Ocelot and ASTRA. Ideally, these would also test that Cheetah remains fast.

### Motivation

So far I have been using Notebooks in the `test` directory to roughly make sure that Cheetah still works when I changed things. This is obviously terrible, as it does not test everything, many of the Notebooks are out of date and it is a lot of work to run.

**Comment by cr-xu** [comment]
Now that Felix is working on improving the code, establishing unit tests becomes more prominent so that we could have a CI/CD pipeline for PRs.

I'll try to add more tests in the upcoming weeks.

**Comment by jank324** [comment]
Agreed! I've already talked to him that this is definitely something we should focus on next.

**Comment by jank324** [comment]
We should use [pytest](https://docs.pytest.org/en/7.2.x/) for testing

**Comment by jank324** [comment]
Btw, the `test` directory already has a couple of notebooks that I have used for testing. Many of them can probably be translated to "proper" pytest tests.
