### ISSUE TITLE
Add charge in the Beam classes

### ISSUE THREAD

**Issue by cr-xu** [desy-ml/cheetah#85]
This is probably an important feature that is overlooked.

Since `ParticleBeam` tracks macroparticles, it might make sense to add a `charge` associated with each particle. This could open possibilities for additional physical process modules (collective effect etc.).

`ParameterBeam` will just have something like a `q_total`.

**Comment by jank324** [comment]
I was actually thinking about the same, because it would also open the door to crude space charge estimations. I would prefer more descriptive variable names (e.g. `total_charge`) though. Or in Bmad they choose the charge based on particle species, which is also interesting.

**Comment by cr-xu** [comment]
`total_charge` sounds good. I would still decouple the `charge` from the particle species because the idea of using macroparticles is that each one of them would represent N real particles.

**Comment by jank324** [comment]
Good point. If we want to, an option would be to later introduce sort of a macro ... where you can pass the species and it will figure out the per particle charge on its own.

I would actually say, both beam classes get a parameter and argument `charge`. `ParameterBeam` just saves this. `ParticleBeam` if only `charge` is passed derives `num_particles` from that, assuming electrons for the time being. The other way round, if you only pass `num_particles`, it figures out the charge. If you pass both, it just takes them as passed. And then maybe `ParticleBeam` should have an `@property` for `single_particle_charge` (I prefer this to `total_charge`).

Thoughts?

**Comment by cr-xu** [comment]
That's not necessarily the case, in a lot of particle tracking codes, one _macroparticle_ actually represents a collection of particles. 
So it's allowed to have different charge `q` per macroparticle, even in most of the cases the macroparticles contain the same charge $q = Q_\text{total}/N_\text{macro}$. 
The total_charge (physical quantity) is not related to the number of macroparticles used for tracking (w.r.t. computational resources)
The true number of electrons is derived $N_\text{e} = Q_\text{total}/ q_\text{e}$
